#!/usr/bin/env bash

set -x

SERVICES=$(docker compose config --services | grep $1)

if [ -z "${SERVICES}" ]
then
    echo "service not found"
    exit 1
fi

docker compose up -d --no-deps --force-recreate $SERVICES
